export const RECITERS = [
  {
    id: "alafasy",
    name: "Mishary Rashid Alafasy",
    arabicName: "مشاري راشد العفاسي",
    style: "Murattal (Clear Melodic)",
    serverCode: "ar.alafasy",
  },
  {
    id: "abdulbasit",
    name: "Abdul Basit Abdul Samad",
    arabicName: "عبد الباسط عبد الصمد",
    style: "Murattal (Classical Resonant)",
    serverCode: "ar.abdulbasitmurattal",
  },
  {
    id: "muhammadayyoub",
    name: "Muhammad Ayyoub",
    arabicName: "محمد أيوب",
    style: "Former Imam of Masjid An-Nabawi",
    serverCode: "ar.muhammadayyoub",
  },
  {
    id: "aljuhaify",
    name: "Ali Al-Hudhaify",
    arabicName: "علي بن عبدالرحمن الحذيفي",
    style: "Imam of Masjid An-Nabawi",
    serverCode: "ar.hudhaify",
  },
  {
    id: "saoodshuraym",
    name: "Saud Al-Shuraim",
    arabicName: "سعود الشريم",
    style: "Haram Makkah (Fast Rhythmic)",
    serverCode: "ar.saoodshuraym",
  },
  {
    id: "ajamy",
    name: "Ahmed Al-Ajamy",
    arabicName: "أحمد بن علي العجمي",
    style: "Clear, Measured Recitation",
    serverCode: "ar.ahmedajamy",
  },
  {
    id: "husary",
    name: "Mahmoud Khalil Al-Husary",
    arabicName: "محمود خليل الحصري",
    style: "Mu'allim (Master of Tajweed)",
    serverCode: "ar.husary",
  },
  {
    id: "mahermuaiqly",
    name: "Maher Al-Muaiqly",
    arabicName: "ماهر المعيقلي",
    style: "Imam of Masjid Al-Haram",
    serverCode: "ar.mahermuaiqly",
  },
  {
    id: "shaatree",
    name: "Abu Bakr Ash-Shaatree",
    arabicName: "أبو بكر الشاطري",
    style: "Melodic Reciter",
    serverCode: "ar.shaatree",
  },
  {
    id: "abdurrahmaansudais",
    name: "Abdurrahman As-Sudais",
    arabicName: "عبد الرحمن السديس",
    style: "Chief Imam of Masjid Al-Haram",
    serverCode: "ar.abdurrahmaansudais",
  },
];

export const SURAHS = [
  {
    id: "surah-fatihah",
    number: 1,
    name: "Al-Fatihah",
    englishName: "The Opening",
    arabicName: "الفاتحة",
    ayahCount: 7,
    durationSeconds: 45,
    ayahs: [],
  },
  {
    id: "surah-baqarah",
    number: 2,
    name: "Al-Baqarah",
    englishName: "The Cow",
    arabicName: "البقرة",
    ayahCount: 286,
    durationSeconds: 3600,
    ayahs: [],
  },
  {
    id: "surah-aal-imran",
    number: 3,
    name: "Aal-Imran",
    englishName: "Family of Imran",
    arabicName: "آل عمران",
    ayahCount: 200,
    durationSeconds: 2700,
    ayahs: [],
  },
  {
    id: "surah-nisa",
    number: 4,
    name: "An-Nisa",
    englishName: "The Women",
    arabicName: "النساء",
    ayahCount: 176,
    durationSeconds: 2400,
    ayahs: [],
  },
  {
    id: "surah-maidah",
    number: 5,
    name: "Al-Ma'idah",
    englishName: "The Table Spread",
    arabicName: "المائدة",
    ayahCount: 120,
    durationSeconds: 1800,
    ayahs: [],
  },
  {
    id: "surah-anam",
    number: 6,
    name: "Al-An'am",
    englishName: "The Cattle",
    arabicName: "الأنعام",
    ayahCount: 165,
    durationSeconds: 2200,
    ayahs: [],
  },
  {
    id: "surah-araf",
    number: 7,
    name: "Al-A'raf",
    englishName: "The Heights",
    arabicName: "الأعراف",
    ayahCount: 206,
    durationSeconds: 2600,
    ayahs: [],
  },
  {
    id: "surah-anfal",
    number: 8,
    name: "Al-Anfal",
    englishName: "The Spoils of War",
    arabicName: "الأنفال",
    ayahCount: 75,
    durationSeconds: 1200,
    ayahs: [],
  },
  {
    id: "surah-tawbah",
    number: 9,
    name: "At-Tawbah",
    englishName: "The Repentance",
    arabicName: "التوبة",
    ayahCount: 129,
    durationSeconds: 1900,
    ayahs: [],
  },
  {
    id: "surah-yunus",
    number: 10,
    name: "Yunus",
    englishName: "Jonah",
    arabicName: "يونس",
    ayahCount: 109,
    durationSeconds: 1600,
    ayahs: [],
  },
  {
    id: "surah-hud",
    number: 11,
    name: "Hud",
    englishName: "Hud",
    arabicName: "هود",
    ayahCount: 123,
    durationSeconds: 1800,
    ayahs: [],
  },
  {
    id: "surah-yusuf",
    number: 12,
    name: "Yusuf",
    englishName: "Joseph",
    arabicName: "يوسف",
    ayahCount: 111,
    durationSeconds: 1700,
    ayahs: [],
  },
  {
    id: "surah-rad",
    number: 13,
    name: "Ar-Ra'd",
    englishName: "The Thunder",
    arabicName: "الرعد",
    ayahCount: 43,
    durationSeconds: 700,
    ayahs: [],
  },
  {
    id: "surah-ibrahim",
    number: 14,
    name: "Ibrahim",
    englishName: "Abraham",
    arabicName: "إبراهيم",
    ayahCount: 52,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-hijr",
    number: 15,
    name: "Al-Hijr",
    englishName: "The Rocky Tract",
    arabicName: "الحجر",
    ayahCount: 99,
    durationSeconds: 1400,
    ayahs: [],
  },
  {
    id: "surah-nahl",
    number: 16,
    name: "An-Nahl",
    englishName: "The Bee",
    arabicName: "النحل",
    ayahCount: 128,
    durationSeconds: 1900,
    ayahs: [],
  },
  {
    id: "surah-isra",
    number: 17,
    name: "Al-Isra",
    englishName: "The Night Journey",
    arabicName: "الإسراء",
    ayahCount: 111,
    durationSeconds: 1700,
    ayahs: [],
  },
  {
    id: "surah-kahf",
    number: 18,
    name: "Al-Kahf",
    englishName: "The Cave",
    arabicName: "الكهف",
    ayahCount: 110,
    durationSeconds: 1700,
    ayahs: [],
  },
  {
    id: "surah-maryam",
    number: 19,
    name: "Maryam",
    englishName: "Mary",
    arabicName: "مريم",
    ayahCount: 98,
    durationSeconds: 1500,
    ayahs: [],
  },
  {
    id: "surah-taha",
    number: 20,
    name: "Ta-Ha",
    englishName: "Ta-Ha",
    arabicName: "طه",
    ayahCount: 135,
    durationSeconds: 2000,
    ayahs: [],
  },
  {
    id: "surah-anbiya",
    number: 21,
    name: "Al-Anbiya",
    englishName: "The Prophets",
    arabicName: "الأنبياء",
    ayahCount: 112,
    durationSeconds: 1700,
    ayahs: [],
  },
  {
    id: "surah-hajj",
    number: 22,
    name: "Al-Hajj",
    englishName: "The Pilgrimage",
    arabicName: "الحج",
    ayahCount: 78,
    durationSeconds: 1200,
    ayahs: [],
  },
  {
    id: "surah-muminun",
    number: 23,
    name: "Al-Mu'minun",
    englishName: "The Believers",
    arabicName: "المؤمنون",
    ayahCount: 118,
    durationSeconds: 1800,
    ayahs: [],
  },
  {
    id: "surah-nur",
    number: 24,
    name: "An-Nur",
    englishName: "The Light",
    arabicName: "النور",
    ayahCount: 64,
    durationSeconds: 1000,
    ayahs: [],
  },
  {
    id: "surah-furqan",
    number: 25,
    name: "Al-Furqan",
    englishName: "The Criterion",
    arabicName: "الفرقان",
    ayahCount: 77,
    durationSeconds: 1200,
    ayahs: [],
  },
  {
    id: "surah-shuara",
    number: 26,
    name: "Ash-Shu'ara",
    englishName: "The Poets",
    arabicName: "الشعراء",
    ayahCount: 227,
    durationSeconds: 2800,
    ayahs: [],
  },
  {
    id: "surah-naml",
    number: 27,
    name: "An-Naml",
    englishName: "The Ant",
    arabicName: "النمل",
    ayahCount: 93,
    durationSeconds: 1400,
    ayahs: [],
  },
  {
    id: "surah-qasas",
    number: 28,
    name: "Al-Qasas",
    englishName: "The Stories",
    arabicName: "القصص",
    ayahCount: 88,
    durationSeconds: 1300,
    ayahs: [],
  },
  {
    id: "surah-ankabut",
    number: 29,
    name: "Al-Ankabut",
    englishName: "The Spider",
    arabicName: "العنكبوت",
    ayahCount: 69,
    durationSeconds: 1100,
    ayahs: [],
  },
  {
    id: "surah-rum",
    number: 30,
    name: "Ar-Rum",
    englishName: "The Romans",
    arabicName: "الروم",
    ayahCount: 60,
    durationSeconds: 950,
    ayahs: [],
  },
  {
    id: "surah-luqman",
    number: 31,
    name: "Luqman",
    englishName: "Luqman",
    arabicName: "لقمان",
    ayahCount: 34,
    durationSeconds: 550,
    ayahs: [],
  },
  {
    id: "surah-sajdah",
    number: 32,
    name: "As-Sajdah",
    englishName: "The Prostration",
    arabicName: "السجدة",
    ayahCount: 30,
    durationSeconds: 500,
    ayahs: [],
  },
  {
    id: "surah-ahzab",
    number: 33,
    name: "Al-Ahzab",
    englishName: "The Combined Forces",
    arabicName: "الأحزاب",
    ayahCount: 73,
    durationSeconds: 1150,
    ayahs: [],
  },
  {
    id: "surah-saba",
    number: 34,
    name: "Saba",
    englishName: "Sheba",
    arabicName: "سبأ",
    ayahCount: 54,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-fatir",
    number: 35,
    name: "Fatir",
    englishName: "The Originator",
    arabicName: "فاطر",
    ayahCount: 45,
    durationSeconds: 720,
    ayahs: [],
  },
  {
    id: "surah-yasin",
    number: 36,
    name: "Ya-Sin",
    englishName: "Ya Sin",
    arabicName: "يس",
    ayahCount: 83,
    durationSeconds: 1250,
    ayahs: [],
  },
  {
    id: "surah-saffat",
    number: 37,
    name: "As-Saffat",
    englishName: "Those Who Set the Ranks",
    arabicName: "الصافات",
    ayahCount: 182,
    durationSeconds: 2300,
    ayahs: [],
  },
  {
    id: "surah-sad",
    number: 38,
    name: "Sad",
    englishName: "The Letter Sad",
    arabicName: "ص",
    ayahCount: 88,
    durationSeconds: 1300,
    ayahs: [],
  },
  {
    id: "surah-zumar",
    number: 39,
    name: "Az-Zumar",
    englishName: "The Troops",
    arabicName: "الزمر",
    ayahCount: 75,
    durationSeconds: 1200,
    ayahs: [],
  },
  {
    id: "surah-ghafir",
    number: 40,
    name: "Ghafir",
    englishName: "The Forgiver",
    arabicName: "غافر",
    ayahCount: 85,
    durationSeconds: 1300,
    ayahs: [],
  },
  {
    id: "surah-fussilat",
    number: 41,
    name: "Fussilat",
    englishName: "Explained in Detail",
    arabicName: "فصلت",
    ayahCount: 54,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-shura",
    number: 42,
    name: "Ash-Shura",
    englishName: "The Consultation",
    arabicName: "الشورى",
    ayahCount: 53,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-zukhruf",
    number: 43,
    name: "Az-Zukhruf",
    englishName: "The Gold Adornments",
    arabicName: "الزخرف",
    ayahCount: 89,
    durationSeconds: 1350,
    ayahs: [],
  },
  {
    id: "surah-dukhan",
    number: 44,
    name: "Ad-Dukhan",
    englishName: "The Smoke",
    arabicName: "الدخان",
    ayahCount: 59,
    durationSeconds: 900,
    ayahs: [],
  },
  {
    id: "surah-jathiyah",
    number: 45,
    name: "Al-Jathiyah",
    englishName: "The Kneeling",
    arabicName: "الجاثية",
    ayahCount: 37,
    durationSeconds: 580,
    ayahs: [],
  },
  {
    id: "surah-ahqaf",
    number: 46,
    name: "Al-Ahqaf",
    englishName: "The Wind-Curved Sandhills",
    arabicName: "الأحقاف",
    ayahCount: 35,
    durationSeconds: 550,
    ayahs: [],
  },
  {
    id: "surah-muhammad",
    number: 47,
    name: "Muhammad",
    englishName: "Muhammad",
    arabicName: "محمد",
    ayahCount: 38,
    durationSeconds: 600,
    ayahs: [],
  },
  {
    id: "surah-fath",
    number: 48,
    name: "Al-Fath",
    englishName: "The Victory",
    arabicName: "الفتح",
    ayahCount: 29,
    durationSeconds: 480,
    ayahs: [],
  },
  {
    id: "surah-hujurat",
    number: 49,
    name: "Al-Hujurat",
    englishName: "The Rooms",
    arabicName: "الحجرات",
    ayahCount: 18,
    durationSeconds: 300,
    ayahs: [],
  },
  {
    id: "surah-qaf",
    number: 50,
    name: "Qaf",
    englishName: "The Letter Qaf",
    arabicName: "ق",
    ayahCount: 45,
    durationSeconds: 700,
    ayahs: [],
  },
  {
    id: "surah-dhariyat",
    number: 51,
    name: "Adh-Dhariyat",
    englishName: "The Winnowing Winds",
    arabicName: "الذاريات",
    ayahCount: 60,
    durationSeconds: 900,
    ayahs: [],
  },
  {
    id: "surah-tur",
    number: 52,
    name: "At-Tur",
    englishName: "The Mount",
    arabicName: "الطور",
    ayahCount: 49,
    durationSeconds: 750,
    ayahs: [],
  },
  {
    id: "surah-najm",
    number: 53,
    name: "An-Najm",
    englishName: "The Star",
    arabicName: "النجم",
    ayahCount: 62,
    durationSeconds: 950,
    ayahs: [],
  },
  {
    id: "surah-qamar",
    number: 54,
    name: "Al-Qamar",
    englishName: "The Moon",
    arabicName: "القمر",
    ayahCount: 55,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-rahman",
    number: 55,
    name: "Ar-Rahman",
    englishName: "The Beneficent",
    arabicName: "الرحمن",
    ayahCount: 78,
    durationSeconds: 1200,
    ayahs: [],
  },
  {
    id: "surah-waqiah",
    number: 56,
    name: "Al-Waqi'ah",
    englishName: "The Inevitable",
    arabicName: "الواقعة",
    ayahCount: 96,
    durationSeconds: 1450,
    ayahs: [],
  },
  {
    id: "surah-hadid",
    number: 57,
    name: "Al-Hadid",
    englishName: "The Iron",
    arabicName: "الحديد",
    ayahCount: 29,
    durationSeconds: 480,
    ayahs: [],
  },
  {
    id: "surah-mujadila",
    number: 58,
    name: "Al-Mujadila",
    englishName: "The Pleading Woman",
    arabicName: "المجادلة",
    ayahCount: 22,
    durationSeconds: 380,
    ayahs: [],
  },
  {
    id: "surah-hashr",
    number: 59,
    name: "Al-Hashr",
    englishName: "The Exile",
    arabicName: "الحشر",
    ayahCount: 24,
    durationSeconds: 400,
    ayahs: [],
  },
  {
    id: "surah-mumtahanah",
    number: 60,
    name: "Al-Mumtahanah",
    englishName: "She That is to be Examined",
    arabicName: "الممتحنة",
    ayahCount: 13,
    durationSeconds: 220,
    ayahs: [],
  },
  {
    id: "surah-saff",
    number: 61,
    name: "As-Saff",
    englishName: "The Ranks",
    arabicName: "الصف",
    ayahCount: 14,
    durationSeconds: 240,
    ayahs: [],
  },
  {
    id: "surah-jumuah",
    number: 62,
    name: "Al-Jumu'ah",
    englishName: "The Congregation",
    arabicName: "الجمعة",
    ayahCount: 11,
    durationSeconds: 180,
    ayahs: [],
  },
  {
    id: "surah-munafiqun",
    number: 63,
    name: "Al-Munafiqun",
    englishName: "The Hypocrites",
    arabicName: "المنافقون",
    ayahCount: 11,
    durationSeconds: 180,
    ayahs: [],
  },
  {
    id: "surah-taghabun",
    number: 64,
    name: "At-Taghabun",
    englishName: "The Mutual Disillusion",
    arabicName: "التغابن",
    ayahCount: 18,
    durationSeconds: 300,
    ayahs: [],
  },
  {
    id: "surah-talaq",
    number: 65,
    name: "At-Talaq",
    englishName: "The Divorce",
    arabicName: "الطلاق",
    ayahCount: 12,
    durationSeconds: 200,
    ayahs: [],
  },
  {
    id: "surah-tahrim",
    number: 66,
    name: "At-Tahrim",
    englishName: "The Prohibition",
    arabicName: "التحريم",
    ayahCount: 12,
    durationSeconds: 200,
    ayahs: [],
  },
  {
    id: "surah-mulk",
    number: 67,
    name: "Al-Mulk",
    englishName: "The Sovereignty",
    arabicName: "الملك",
    ayahCount: 30,
    durationSeconds: 500,
    ayahs: [],
  },
  {
    id: "surah-qalam",
    number: 68,
    name: "Al-Qalam",
    englishName: "The Pen",
    arabicName: "القلم",
    ayahCount: 52,
    durationSeconds: 800,
    ayahs: [],
  },
  {
    id: "surah-haqqah",
    number: 69,
    name: "Al-Haqqah",
    englishName: "The Reality",
    arabicName: "الحاقة",
    ayahCount: 52,
    durationSeconds: 800,
    ayahs: [],
  },
  {
    id: "surah-maarij",
    number: 70,
    name: "Al-Ma'arij",
    englishName: "The Ascending Stairways",
    arabicName: "المعارج",
    ayahCount: 44,
    durationSeconds: 700,
    ayahs: [],
  },
  {
    id: "surah-nuh",
    number: 71,
    name: "Nuh",
    englishName: "Noah",
    arabicName: "نوح",
    ayahCount: 28,
    durationSeconds: 450,
    ayahs: [],
  },
  {
    id: "surah-jinn",
    number: 72,
    name: "Al-Jinn",
    englishName: "The Jinn",
    arabicName: "الجن",
    ayahCount: 28,
    durationSeconds: 450,
    ayahs: [],
  },
  {
    id: "surah-muzzammil",
    number: 73,
    name: "Al-Muzzammil",
    englishName: "The Enshrouded One",
    arabicName: "المزمل",
    ayahCount: 20,
    durationSeconds: 320,
    ayahs: [],
  },
  {
    id: "surah-muddaththir",
    number: 74,
    name: "Al-Muddaththir",
    englishName: "The Cloaked One",
    arabicName: "المدثر",
    ayahCount: 56,
    durationSeconds: 850,
    ayahs: [],
  },
  {
    id: "surah-qiyamah",
    number: 75,
    name: "Al-Qiyamah",
    englishName: "The Resurrection",
    arabicName: "القيامة",
    ayahCount: 40,
    durationSeconds: 620,
    ayahs: [],
  },
  {
    id: "surah-insan",
    number: 76,
    name: "Al-Insan",
    englishName: "The Man",
    arabicName: "الإنسان",
    ayahCount: 31,
    durationSeconds: 500,
    ayahs: [],
  },
  {
    id: "surah-mursalat",
    number: 77,
    name: "Al-Mursalat",
    englishName: "The Emissaries",
    arabicName: "المرسلات",
    ayahCount: 50,
    durationSeconds: 780,
    ayahs: [],
  },
  {
    id: "surah-naba",
    number: 78,
    name: "An-Naba",
    englishName: "The Tidings",
    arabicName: "النبأ",
    ayahCount: 40,
    durationSeconds: 620,
    ayahs: [],
  },
  {
    id: "surah-naziat",
    number: 79,
    name: "An-Nazi'at",
    englishName: "Those Who Drag Forth",
    arabicName: "النازعات",
    ayahCount: 46,
    durationSeconds: 720,
    ayahs: [],
  },
  {
    id: "surah-abasa",
    number: 80,
    name: "Abasa",
    englishName: "He Frowned",
    arabicName: "عبس",
    ayahCount: 42,
    durationSeconds: 650,
    ayahs: [],
  },
  {
    id: "surah-takwir",
    number: 81,
    name: "At-Takwir",
    englishName: "The Overthrowing",
    arabicName: "التكوير",
    ayahCount: 29,
    durationSeconds: 450,
    ayahs: [],
  },
  {
    id: "surah-infitar",
    number: 82,
    name: "Al-Infitar",
    englishName: "The Cleaving",
    arabicName: "الإنفطار",
    ayahCount: 19,
    durationSeconds: 300,
    ayahs: [],
  },
  {
    id: "surah-mutaffifin",
    number: 83,
    name: "Al-Mutaffifin",
    englishName: "The Defrauding",
    arabicName: "المطففين",
    ayahCount: 36,
    durationSeconds: 560,
    ayahs: [],
  },
  {
    id: "surah-inshiqaq",
    number: 84,
    name: "Al-Inshiqaq",
    englishName: "The Splitting Open",
    arabicName: "الإنشقاق",
    ayahCount: 25,
    durationSeconds: 400,
    ayahs: [],
  },
  {
    id: "surah-buruj",
    number: 85,
    name: "Al-Buruj",
    englishName: "The Mansions of the Stars",
    arabicName: "البروج",
    ayahCount: 22,
    durationSeconds: 360,
    ayahs: [],
  },
  {
    id: "surah-tariq",
    number: 86,
    name: "At-Tariq",
    englishName: "The Nightcomer",
    arabicName: "الطارق",
    ayahCount: 17,
    durationSeconds: 280,
    ayahs: [],
  },
  {
    id: "surah-ala",
    number: 87,
    name: "Al-A'la",
    englishName: "The Most High",
    arabicName: "الأعلى",
    ayahCount: 19,
    durationSeconds: 300,
    ayahs: [],
  },
  {
    id: "surah-ghashiyah",
    number: 88,
    name: "Al-Ghashiyah",
    englishName: "The Overwhelming",
    arabicName: "الغاشية",
    ayahCount: 26,
    durationSeconds: 420,
    ayahs: [],
  },
  {
    id: "surah-fajr",
    number: 89,
    name: "Al-Fajr",
    englishName: "The Dawn",
    arabicName: "الفجر",
    ayahCount: 30,
    durationSeconds: 480,
    ayahs: [],
  },
  {
    id: "surah-balad",
    number: 90,
    name: "Al-Balad",
    englishName: "The City",
    arabicName: "البلد",
    ayahCount: 20,
    durationSeconds: 320,
    ayahs: [],
  },
  {
    id: "surah-shams",
    number: 91,
    name: "Ash-Shams",
    englishName: "The Sun",
    arabicName: "الشمس",
    ayahCount: 15,
    durationSeconds: 250,
    ayahs: [],
  },
  {
    id: "surah-layl",
    number: 92,
    name: "Al-Layl",
    englishName: "The Night",
    arabicName: "الليل",
    ayahCount: 21,
    durationSeconds: 340,
    ayahs: [],
  },
  {
    id: "surah-duha",
    number: 93,
    name: "Ad-Duha",
    englishName: "The Morning Hours",
    arabicName: "الضحى",
    ayahCount: 11,
    durationSeconds: 180,
    ayahs: [],
  },
  {
    id: "surah-sharh",
    number: 94,
    name: "Ash-Sharh",
    englishName: "The Relief",
    arabicName: "الشرح",
    ayahCount: 8,
    durationSeconds: 130,
    ayahs: [],
  },
  {
    id: "surah-tin",
    number: 95,
    name: "At-Tin",
    englishName: "The Fig",
    arabicName: "التين",
    ayahCount: 8,
    durationSeconds: 130,
    ayahs: [],
  },
  {
    id: "surah-alaq",
    number: 96,
    name: "Al-Alaq",
    englishName: "The Clot",
    arabicName: "العلق",
    ayahCount: 19,
    durationSeconds: 300,
    ayahs: [],
  },
  {
    id: "surah-qadr",
    number: 97,
    name: "Al-Qadr",
    englishName: "The Power",
    arabicName: "القدر",
    ayahCount: 5,
    durationSeconds: 80,
    ayahs: [],
  },
  {
    id: "surah-bayyinah",
    number: 98,
    name: "Al-Bayyinah",
    englishName: "The Clear Proof",
    arabicName: "البينة",
    ayahCount: 8,
    durationSeconds: 130,
    ayahs: [],
  },
  {
    id: "surah-zalzalah",
    number: 99,
    name: "Az-Zalzalah",
    englishName: "The Earthquake",
    arabicName: "الزلزلة",
    ayahCount: 8,
    durationSeconds: 130,
    ayahs: [],
  },
  {
    id: "surah-adiyat",
    number: 100,
    name: "Al-Adiyat",
    englishName: "The Courser",
    arabicName: "العاديات",
    ayahCount: 11,
    durationSeconds: 180,
    ayahs: [],
  },
  {
    id: "surah-qariah",
    number: 101,
    name: "Al-Qari'ah",
    englishName: "The Calamity",
    arabicName: "القارعة",
    ayahCount: 11,
    durationSeconds: 180,
    ayahs: [],
  },
  {
    id: "surah-takathur",
    number: 102,
    name: "At-Takathur",
    englishName: "The Rivalry in World Increase",
    arabicName: "التكاثر",
    ayahCount: 8,
    durationSeconds: 130,
    ayahs: [],
  },
  {
    id: "surah-asr",
    number: 103,
    name: "Al-Asr",
    englishName: "The Declining Day",
    arabicName: "العصر",
    ayahCount: 3,
    durationSeconds: 50,
    ayahs: [],
  },
  {
    id: "surah-humazah",
    number: 104,
    name: "Al-Humazah",
    englishName: "The Traducer",
    arabicName: "الهمزة",
    ayahCount: 9,
    durationSeconds: 150,
    ayahs: [],
  },
  {
    id: "surah-fil",
    number: 105,
    name: "Al-Fil",
    englishName: "The Elephant",
    arabicName: "الفيل",
    ayahCount: 5,
    durationSeconds: 80,
    ayahs: [],
  },
  {
    id: "surah-quraysh",
    number: 106,
    name: "Quraysh",
    englishName: "Quraysh",
    arabicName: "قريش",
    ayahCount: 4,
    durationSeconds: 65,
    ayahs: [],
  },
  {
    id: "surah-maun",
    number: 107,
    name: "Al-Ma'un",
    englishName: "The Small Kindnesses",
    arabicName: "الماعون",
    ayahCount: 7,
    durationSeconds: 110,
    ayahs: [],
  },
  {
    id: "surah-kawthar",
    number: 108,
    name: "Al-Kawthar",
    englishName: "The Abundance",
    arabicName: "الكوثر",
    ayahCount: 3,
    durationSeconds: 50,
    ayahs: [],
  },
  {
    id: "surah-kafirun",
    number: 109,
    name: "Al-Kafirun",
    englishName: "The Disbelievers",
    arabicName: "الكافرون",
    ayahCount: 6,
    durationSeconds: 95,
    ayahs: [],
  },
  {
    id: "surah-nasr",
    number: 110,
    name: "An-Nasr",
    englishName: "The Divine Support",
    arabicName: "النصر",
    ayahCount: 3,
    durationSeconds: 50,
    ayahs: [],
  },
  {
    id: "surah-masad",
    number: 111,
    name: "Al-Masad",
    englishName: "The Palm Fiber",
    arabicName: "المسد",
    ayahCount: 5,
    durationSeconds: 80,
    ayahs: [],
  },
  {
    id: "surah-ikhlas",
    number: 112,
    name: "Al-Ikhlas",
    englishName: "The Sincerity",
    arabicName: "الإخلاص",
    ayahCount: 4,
    durationSeconds: 65,
    ayahs: [],
  },
  {
    id: "surah-falaq",
    number: 113,
    name: "Al-Falaq",
    englishName: "The Daybreak",
    arabicName: "الفلق",
    ayahCount: 5,
    durationSeconds: 80,
    ayahs: [],
  },
  {
    id: "surah-nas",
    number: 114,
    name: "An-Nas",
    englishName: "The Mankind",
    arabicName: "الناس",
    ayahCount: 6,
    durationSeconds: 95,
    ayahs: [],
  },
];

export const COURSES = [
  {
    id: "course-tajweed-foundations",
    title: "Tajweed Foundations & Sanad Articulation",
    shortDescription:
      "Master the precise articulation points and rhythmic flow of Quranic recitation.",
    description: "A comprehensive 8-week journey into the science of Tajweed.",
    category: "Quran & Tajweed",
    level: "Beginner",
    price: 180,
    weeksCount: 8,
    lessonsCount: 24,
    rating: 4.9,
    reviewCount: 128,
    badge: "Sanad Track",
  },
  {
    id: "course-arabic-grammar",
    title: "Quranic Arabic Grammar Masterclass",
    shortDescription:
      "Unlock the linguistic miracle of the Quran through classical Arabic grammar.",
    description: "Dive deep into Nahw and Sarf through the lens of the Quran.",
    category: "Arabic Language",
    level: "Intermediate",
    price: 220,
    weeksCount: 10,
    lessonsCount: 30,
    rating: 4.8,
    reviewCount: 95,
    badge: "Most Popular",
  },
  {
    id: "course-fiqh",
    title: "Fiqh of Worship & Daily Life",
    shortDescription: "Practical Islamic jurisprudence for the modern seeker.",
    description:
      "A comprehensive study of Fiqh according to classical and contemporary scholarship.",
    category: "Islamic Jurisprudence",
    level: "Intermediate",
    price: 200,
    weeksCount: 12,
    lessonsCount: 36,
    rating: 4.7,
    reviewCount: 88,
    badge: "Scholar Series",
  },
];
