export const Icons = {
  play: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>',
  pause: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>',
  search: '🔍',
  headphones: '🎧',
  award: '🏆',
  shieldCheck: '🛡️',
  database: '💾',
  mic: '🎤',
  bookOpen: '📖',
  arrowRight: '→',
  arrowLeft: '←',
  chevronDown: '▼',
  check: '✓',
  x: '✕',
  logOut: '🚪',
  google: 'G',
  trash: '🗑️',
  bookmark: '🔖',
  plus: '+',
  sparkles: '✨',
  creditCard: '💳',
  download: '⬇️',
  menu: '☰'
};