export const RECITERS = [
  {
    id: "alafasy",
    name: "Mishary Rashid Alafasy",
    arabicName: "مشاري راشد العفاسي",
    style: "Murattal (Clear Melodic)",
    serverCode: "ar.alafasy",
  },
  {
    id: "abdulbasit",
    name: "Abdul Basit Abdul Samad",
    arabicName: "عبد الباسط عبد الصمد",
    style: "Murattal (Classical Resonant)",
    serverCode: "ar.abdulbasitmurattal",
  },
  {
    id: "muhammadayyoub",
    name: "Muhammad Ayyub",
    arabicName: "محمد أيوب",
    style: "Former Imam of Masjid An-Nabawi",
    serverCode: "ar.muhammadayyoub",
  },
  {
    id: "yasserdosari",
    name: "Yasser Al-Dosari",
    arabicName: "ياسر الدوسري",
    style: "Current Imam of Masjid Al-Haram",
    serverCode: "ar.yasserdosari",
  },
  {
    id: "saoodshuraym",
    name: "Saud Al-Shuraim",
    arabicName: "سعود الشريم",
    style: "Haram Makkah (Fast Rhythmic)",
    serverCode: "ar.saoodshuraym",
  },
  {
    id: "aljuhany",
    name: "Abdullah Al-Juhany",
    arabicName: "عبد الله الجهني",
    style: "Imam of Masjid Al-Haram",
    serverCode: "ar.abdullahaljuhany",
  },
  {
    id: "husary",
    name: "Mahmoud Khalil Al-Husary",
    arabicName: "محمود خليل الحصري",
    style: "Mu'allim (Master of Tajweed)",
    serverCode: "ar.husary",
  },
  {
    id: "mahermuaiqly",
    name: "Maher Al-Muaiqly",
    arabicName: "ماهر المعيقلي",
    style: "Imam of Masjid Al-Haram",
    serverCode: "ar.mahermuaiqly",
  },
  {
    id: "saadalghamidi",
    name: "Saad Al-Ghamdi",
    arabicName: "سعد الغامدي",
    style: "Deep Resonant Khushu'",
    serverCode: "ar.saadalghamidi",
  },
  {
    id: "abdurrahmaansudais",
    name: "Abdurrahman As-Sudais",
    arabicName: "عبد الرحمن السديس",
    style: "Chief Imam of Masjid Al-Haram",
    serverCode: "ar.abdurrahmaansudais",
  },
];