export const RECITERS = [
  {
    id: "alafasy",
    name: "Mishary Rashid Alafasy",
    arabicName: "مشاري راشد العفاسي",
    style: "Murattal (Clear Melodic)",
    serverCode: "ar.alafasy",
  },
  {
    id: "abdulbasit",
    name: "Abdul Basit Abdul Samad",
    arabicName: "عبد الباسط عبد الصمد",
    style: "Murattal (Classical Resonant)",
    serverCode: "ar.abdulbasitmurattal",
  },
  {
    id: "muhammadayyoub",
    name: "Muhammad Ayyoub",
    arabicName: "محمد أيوب",
    style: "Former Imam of Masjid An-Nabawi",
    serverCode: "ar.muhammadayyoub",
  },
  {
    id: "aljuhaify",
    name: "Ali Al-Hudhaify",
    arabicName: "علي بن عبدالرحمن الحذيفي",
    style: "Imam of Masjid An-Nabawi",
    serverCode: "ar.hudhaify",
  },
  {
    id: "saoodshuraym",
    name: "Saud Al-Shuraim",
    arabicName: "سعود الشريم",
    style: "Haram Makkah (Fast Rhythmic)",
    serverCode: "ar.saoodshuraym",
  },
  {
    id: "ajamy",
    name: "Ahmed Al-Ajamy",
    arabicName: "أحمد بن علي العجمي",
    style: "Clear, Measured Recitation",
    serverCode: "ar.ahmedajamy",
  },
  {
    id: "husary",
    name: "Mahmoud Khalil Al-Husary",
    arabicName: "محمود خليل الحصري",
    style: "Mu'allim (Master of Tajweed)",
    serverCode: "ar.husary",
  },
  {
    id: "mahermuaiqly",
    name: "Maher Al-Muaiqly",
    arabicName: "ماهر المعيقلي",
    style: "Imam of Masjid Al-Haram",
    serverCode: "ar.mahermuaiqly",
  },
  {
    id: "shaatree",
    name: "Abu Bakr Ash-Shaatree",
    arabicName: "أبو بكر الشاطري",
    style: "Melodic Reciter",
    serverCode: "ar.shaatree",
  },
  {
    id: "abdurrahmaansudais",
    name: "Abdurrahman As-Sudais",
    arabicName: "عبد الرحمن السديس",
    style: "Chief Imam of Masjid Al-Haram",
    serverCode: "ar.abdurrahmaansudais",
  },
];